### ISSUE TITLE
Remove dependency on @janeirodigital/interop-utils

### ISSUE THREAD

**Issue by elf-pavlik** [o-development/solid-notification-client#6]
### TODO

* [ ] use [`http-link-header`](https://www.npmjs.com/package/http-link-header) directly
* [ ] use some RDF methods directly from [`n3`](https://www.npmjs.com/package/n3)
* [ ]  include minimal `NOTIFY` namespace locally
